version: "2"

services:
  web:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./src:/app
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    restart: always
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
volumes:
  pgdata: