# Generated by Django 2.2.3 on 2019-07-03 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190703_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineitem',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='lineitem',
            old_name='order_id',
            new_name='order',
        ),
        migrations.AlterUniqueTogether(
            name='lineitem',
            unique_together={('order', 'item')},
        ),
    ]
